name = "PyPinYin"
uuid = "8c847028-23a0-4102-8c1d-e908a7170008"
authors = ["Sole <sonosole@163.com>"]
version = "0.1.1"
license = "MIT"

[deps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[compat]
julia  = "1"
PyCall = "1"
